/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyect;

import javax.swing.DefaultComboBoxModel;
import static jdk.nashorn.internal.objects.NativeString.trim;

/**
 *
 * @author jose
 */
public class principal extends javax.swing.JFrame {

    List Materiales = new List();
    List Catalogo = new List();
    List Inventario = new List();
    List Empleados = new List();
    List Productos_Inventario=new List();
    List materiales_de_productos=new List();
    Queue ordenes = new Queue();

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMateriales = new javax.swing.JDialog();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        Nombre_Materiales = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Numero_de_seriemateriales = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        marca_matriales = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Dirección_materiales = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<String>();
        jLabel13 = new javax.swing.JLabel();
        NOmbre_materiales_Mod1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        numero_deserie_materiales_mod1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Marca_nmateriales_Mod1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Direccion_materiales_Mod1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jLabel11 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jEmpleados = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Identidad = new javax.swing.JTextField();
        Edad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Direccion = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Identidad_Empleado = new javax.swing.JTextField();
        Nombre_Empleado = new javax.swing.JTextField();
        Direccion_Empleado = new javax.swing.JTextField();
        Edad_Empleado = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        Productos = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Nombre_producto_mod = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Descripcion_producto_mod = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<String>();
        jLabel20 = new javax.swing.JLabel();
        tiempo_producto_mod = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Descripcion_producto = new javax.swing.JTextField();
        Nombre_Producto = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox<String>();
        jLabel40 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        tiempo = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jComboBox6 = new javax.swing.JComboBox<String>();
        jLabel39 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTabbedPane5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane5StateChanged(evt);
            }
        });

        jLabel23.setText("Nombre ");

        Nombre_Materiales.setText("jTextField1");

        jLabel24.setText("Número de Serie");

        Numero_de_seriemateriales.setText("jTextField1");

        jLabel25.setText("Marca");

        marca_matriales.setText("Edad_Empleado");

        jLabel26.setText("Dirección");

        Dirección_materiales.setText("jTextField1");

        jButton8.setText("Agregar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel23))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numero_de_seriemateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre_Materiales, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marca_matriales, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dirección_materiales, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Nombre_Materiales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(Numero_de_seriemateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(marca_matriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(Dirección_materiales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton8)
                .addGap(21, 21, 21))
        );

        jTabbedPane5.addTab("Agregar Materiales", jPanel8);

        jLabel12.setText("Seleccione el empleado a ELiminar");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setText("Nombre ");

        NOmbre_materiales_Mod1.setText("jTextField1");

        jLabel14.setText("Numero de serie");

        numero_deserie_materiales_mod1.setText("jTextField1");

        jLabel15.setText("Marca");

        Marca_nmateriales_Mod1.setText("Edad_Empleado");

        jLabel16.setText("Dirección");

        Direccion_materiales_Mod1.setText("jTextField1");

        jButton9.setText("Modificar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel12)
                .addGap(0, 121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero_deserie_materiales_mod1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion_materiales_Mod1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Marca_nmateriales_Mod1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NOmbre_materiales_Mod1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(NOmbre_materiales_Mod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(numero_deserie_materiales_mod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14)))
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Marca_nmateriales_Mod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion_materiales_Mod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(24, 24, 24))
        );

        jTabbedPane5.addTab("Modificar Materiales", jPanel9);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Seleccione el empleado a ELiminar");

        jButton10.setText("ELiminar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton10)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton10)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("ELiminar Materiales", jPanel10);

        javax.swing.GroupLayout jMaterialesLayout = new javax.swing.GroupLayout(jMateriales.getContentPane());
        jMateriales.getContentPane().setLayout(jMaterialesLayout);
        jMaterialesLayout.setHorizontalGroup(
            jMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMaterialesLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jMaterialesLayout.setVerticalGroup(
            jMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMaterialesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel2.setLayout(null);

        jButton5.setText("Modificar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(170, 346, 75, 23);

        jLabel10.setText("Seleccione el empleado a Modificar");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(120, 20, 240, 14);

        jLabel5.setText("Nombre ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(59, 104, 40, 14);
        jPanel2.add(Nombre);
        Nombre.setBounds(141, 104, 180, 20);

        jLabel6.setText("Identidad");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(60, 170, 46, 14);
        jPanel2.add(Identidad);
        Identidad.setBounds(141, 164, 170, 20);
        jPanel2.add(Edad);
        Edad.setBounds(140, 270, 180, 20);

        jLabel7.setText("Edad");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(59, 278, 24, 14);

        jLabel8.setText("Dirección");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(59, 225, 43, 14);
        jPanel2.add(Direccion);
        Direccion.setBounds(141, 220, 170, 20);

        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(150, 40, 154, 20);

        jTabbedPane1.addTab("Modificar  Empleado", jPanel2);

        jLabel2.setText("Nombre ");

        jLabel3.setText("Identidad");

        jLabel4.setText("Edad");

        jLabel27.setText("Dirección");

        Identidad_Empleado.setText("jTextField1");

        Nombre_Empleado.setText("jTextField1");

        Direccion_Empleado.setText("jTextField1");

        Edad_Empleado.setText("Edad_Empleado");

        jButton7.setText("Agregar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Identidad_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Direccion_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Edad_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Identidad_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Edad_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Direccion_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Empleados", jPanel1);

        jLabel9.setText("Seleccione el empleado a ELiminar");

        jButton6.setText("Eliminar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton6)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton6)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Empleado", jPanel3);

        javax.swing.GroupLayout jEmpleadosLayout = new javax.swing.GroupLayout(jEmpleados.getContentPane());
        jEmpleados.getContentPane().setLayout(jEmpleadosLayout);
        jEmpleadosLayout.setHorizontalGroup(
            jEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEmpleadosLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jEmpleadosLayout.setVerticalGroup(
            jEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jPanel4.setLayout(null);

        jButton11.setText("Modificar");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jPanel4.add(jButton11);
        jButton11.setBounds(160, 260, 75, 23);

        jLabel17.setText("Seleccione el Producto a Modificar");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(120, 20, 240, 14);

        jLabel18.setText("Nombre ");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(59, 104, 40, 14);
        jPanel4.add(Nombre_producto_mod);
        Nombre_producto_mod.setBounds(141, 104, 180, 20);

        jLabel19.setText("Descripción");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(60, 170, 54, 14);
        jPanel4.add(Descripcion_producto_mod);
        Descripcion_producto_mod.setBounds(141, 164, 180, 20);

        jPanel4.add(jComboBox5);
        jComboBox5.setBounds(150, 40, 154, 20);

        jLabel20.setText("Tiempo");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(60, 230, 34, 14);
        jPanel4.add(tiempo_producto_mod);
        tiempo_producto_mod.setBounds(140, 220, 180, 20);

        jTabbedPane2.addTab("Modificar  Producto", jPanel4);

        jLabel22.setText("Nombre ");

        jLabel36.setText("Descripción");

        Descripcion_producto.setText("jTextField1");

        Nombre_Producto.setText("jTextField1");

        jButton12.setText("Agregar");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel40.setText("Agregar materiales");

        jButton14.setText("Agregar Material");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        jLabel21.setText("Tiempo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel40)))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14)
                    .addComponent(jButton12)
                    .addComponent(Descripcion_producto, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(Nombre_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempo))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Nombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(Descripcion_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(54, 54, 54)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(36, 36, 36))
        );

        jTabbedPane2.addTab("Agregar Producto", jPanel5);

        jLabel39.setText("Seleccione el producto a ELiminar");

        jButton13.setText("Eliminar");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel39)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton13)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton13)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar Producto", jPanel6);

        javax.swing.GroupLayout ProductosLayout = new javax.swing.GroupLayout(Productos.getContentPane());
        Productos.getContentPane().setLayout(ProductosLayout);
        ProductosLayout.setHorizontalGroup(
            ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductosLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        ProductosLayout.setVerticalGroup(
            ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductosLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU");

        jButton1.setText("Procesos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Productos ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Empleados");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Materiales");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.jEmpleados.setModal(true);
        this.jEmpleados.pack();
        this.jEmpleados.setLocationRelativeTo(this);
        this.jEmpleados.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jMateriales.setModal(true);
        this.jMateriales.pack();
        this.jMateriales.setLocationRelativeTo(this);
        this.jMateriales.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        empleados empleado = new empleados(this.Nombre_Empleado.getText(), (Integer.parseInt(this.Identidad_Empleado.getText())), (Integer.parseInt(this.Edad_Empleado.getText())), this.Direccion_Empleado.getText());
        Empleados.push_back(empleado);
        Empleados.print();

    }//GEN-LAST:event_jButton7MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (this.jTabbedPane1.getSelectedIndex() == 0) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.jComboBox2.getModel();
            modelo.removeAllElements();
            for (int x = 0; x < Empleados.size(); x++) {
                modelo.addElement(Empleados.elementAt(x).getValue());
            }
        }
        if (this.jTabbedPane1.getSelectedIndex() == 2) {
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.jComboBox1.getModel();
            modelo.removeAllElements();
            for (int x = 0; x < Empleados.size(); x++) {
                modelo.addElement(Empleados.elementAt(x).getValue());
            }
        }


    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked

        Empleados.remove(this.jComboBox1.getSelectedIndex());
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.jComboBox1.getModel();
        modelo.removeAllElements();
        for (int x = 0; x < Empleados.size(); x++) {
            modelo.addElement(Empleados.elementAt(x).getValue());
        }

    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // empleados temp=(empleados)this.jComboBox1.getSelectedItem();
        ((empleados) this.jComboBox2.getSelectedItem()).setNombre(this.Nombre.getText());
        System.out.println(((empleados) (Empleados.elementAt(0).getValue())).toString());
        ((empleados) this.jComboBox2.getSelectedItem()).setIdentidad(Integer.parseInt(this.Identidad.getText()));
        ((empleados) this.jComboBox2.getSelectedItem()).setDireccion(this.Direccion.getText());
       ((empleados) this.jComboBox2.getSelectedItem()).setEdad(Integer.parseInt(this.Edad.getText()));
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        materiales material = new materiales(this.Nombre_Materiales.getText(), this.Dirección_materiales.getText(), this.marca_matriales.getText(), Integer.parseInt(this.Numero_de_seriemateriales.getText()));
        Materiales.push_back(material);
        Node temp = Catalogo.first();
        boolean existe = false;

        int cantidad = 0;
        while (cantidad < Catalogo.size()) {
            if (((materiales) (temp.getValue())).getNombre().equals(trim(this.Nombre_Materiales.getText()))) {
                existe = true;
                break;
            }
            temp = temp.getNext();

            cantidad++;
        }
        cantidad = 0;
        if (existe == true) {
            Node temporal = Inventario.first();
            while (cantidad < Inventario.size()) {
                if ((((materiales) (((Stack) temporal.getValue()).peek())).getNombre()).equals(trim(this.Nombre_Materiales.getText()))) {
                    ((Stack) temporal.getValue()).push_back(material);
                }
                temporal = temporal.getNext();

                cantidad++;
            }
        } else {

            Catalogo.push_back(material);
            Stack nuevo = new Stack(material);
            Inventario.push_back(nuevo);

        }
        Catalogo.print();
        System.out.println("a");
        Materiales.print();
        System.out.println("b");
        System.out.println((Inventario.size()));


    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        Node temp = Materiales.first();
        int cantidad = 0;
        while (cantidad < Materiales.size()) {
            if (((materiales) (temp.getValue())).getNombre().equals(trim((String) this.jComboBox4.getSelectedItem()))) {
                ((materiales) (temp.getValue())).setNombre(trim(this.NOmbre_materiales_Mod1.getText()));
                ((materiales) (temp.getValue())).setMarca(trim(this.Marca_nmateriales_Mod1.getText()));
                ((materiales) (temp.getValue())).setNumero_de_serie(Integer.parseInt(this.numero_deserie_materiales_mod1.getText()));
                ((materiales) (temp.getValue())).setDescripcion(this.Direccion_materiales_Mod1.getText());
            }
            temp = temp.getNext();
            cantidad++;
        }
        Catalogo.print();
        System.out.println("a");
        Materiales.print();
        System.out.println("b");
        System.out.println((Inventario.size()));
    }//GEN-LAST:event_jButton9MouseClicked

    private void jTabbedPane5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane5StateChanged
        if (this.jTabbedPane5.getSelectedIndex() == 1) {
            this.jComboBox4.removeAllItems();
            for (int i = 0; i < Catalogo.size(); i++) {
                this.jComboBox4.addItem(((materiales) Catalogo.elementAt(i).getValue()).getNombre());
            }
        }
        if (this.jTabbedPane5.getSelectedIndex() == 2) {
            this.jComboBox3.removeAllItems();
            for (int i = 0; i < Catalogo.size(); i++) {
                this.jComboBox3.addItem(((materiales) Catalogo.elementAt(i).getValue()).getNombre());
            }
        }

    }//GEN-LAST:event_jTabbedPane5StateChanged

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        int cantidad = 0;
        int contador=0;
        Node temp1=Catalogo.first();
        while (contador < Catalogo.size()) {
            if (((materiales) (temp1.getValue())).getNombre().equals(trim((String) this.jComboBox3.getSelectedItem()))) {
                temp1 = temp1.getNext();
                Catalogo.remove(contador);
                Inventario.remove(contador);
                
            } else {
                temp1 = temp1.getNext();
                
            }
            contador++;
        }
        Node temp = Materiales.first();
        int numero=this.jComboBox3.getSelectedIndex();
        
        while (cantidad < Materiales.size()) {
            if (((materiales) (temp.getValue())).getNombre().equals(trim((String) this.jComboBox3.getSelectedItem()))) {
                temp = temp.getNext();
                Materiales.remove(cantidad);
                
                
            } else {
                temp = temp.getNext();
                
            }
            cantidad++;
        }
        Catalogo.print();
        System.out.println("a");
        Materiales.print();
        System.out.println("b");
        System.out.println((Inventario.size()));        
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        ((productos) this.jComboBox5.getSelectedItem()).setNombre(this.Nombre_producto_mod.getText());
        ((productos) this.jComboBox5.getSelectedItem()).setDescripcion(this.Descripcion_producto_mod.getText());
        ((productos) this.jComboBox5.getSelectedItem()).setTiempo(Integer.parseInt(this.tiempo_producto_mod.getText()));
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        List nueva_lista=new List();
        nueva_lista=materiales_de_productos;
        materiales_de_productos=new List();
        productos producto=new productos(this.Nombre_Producto.getText(),this.Descripcion_producto.getText(),Integer.parseInt(this.tiempo.getText()),nueva_lista);
        Productos_Inventario.push_back(producto);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        Productos_Inventario.remove(this.jComboBox6.getSelectedIndex());
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.jComboBox6.getModel();
        modelo.removeAllElements();
        for (int x = 0; x < Productos_Inventario.size(); x++) {
            modelo.addElement(Productos_Inventario.elementAt(x).getValue());
        }
    }//GEN-LAST:event_jButton13MouseClicked

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        if(this.jTabbedPane2.getSelectedIndex()==0 ){
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.jComboBox5.getModel();
            modelo.removeAllElements();
            for (int x = 0; x < Productos_Inventario.size(); x++) {
                modelo.addElement(Productos_Inventario.elementAt(x).getValue());
            }
        }
         if( this.jTabbedPane2.getSelectedIndex()==2){
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.jComboBox6.getModel();
            modelo.removeAllElements();
            for (int x = 0; x < Productos_Inventario.size(); x++) {
                modelo.addElement(Productos_Inventario.elementAt(x).getValue());
            }
        }
        if( this.jTabbedPane2.getSelectedIndex()==1){
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.jComboBox7.getModel();
            modelo.removeAllElements();
            for (int x = 0; x < Catalogo.size(); x++) {
                modelo.addElement(Catalogo.elementAt(x).getValue());
            }
        } 
        
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
       materiales_de_productos.push_back(this.jComboBox7.getSelectedItem());
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.Productos.setModal(true);
        this.Productos.pack();
        this.Productos.setLocationRelativeTo(this);
        this.Productos.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descripcion_producto;
    private javax.swing.JTextField Descripcion_producto_mod;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Direccion_Empleado;
    private javax.swing.JTextField Direccion_materiales_Mod1;
    private javax.swing.JTextField Dirección_materiales;
    private javax.swing.JTextField Edad;
    private javax.swing.JTextField Edad_Empleado;
    private javax.swing.JTextField Identidad;
    private javax.swing.JTextField Identidad_Empleado;
    private javax.swing.JTextField Marca_nmateriales_Mod1;
    private javax.swing.JTextField NOmbre_materiales_Mod1;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Nombre_Empleado;
    private javax.swing.JTextField Nombre_Materiales;
    private javax.swing.JTextField Nombre_Producto;
    private javax.swing.JTextField Nombre_producto_mod;
    private javax.swing.JTextField Numero_de_seriemateriales;
    private javax.swing.JDialog Productos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JDialog jEmpleados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JDialog jMateriales;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField marca_matriales;
    private javax.swing.JTextField numero_deserie_materiales_mod1;
    private javax.swing.JTextField tiempo;
    private javax.swing.JTextField tiempo_producto_mod;
    // End of variables declaration//GEN-END:variables
}
